"""Add template_subservices table

Revision ID: 1f23450db223
Revises: 8d8a8fa7f3a9
Create Date: 2025-05-06 23:07:43.903867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f23450db223'
down_revision = '8d8a8fa7f3a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_subservices',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('subservice_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subservice_id'], ['sub_services.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['service_templates.id'], ),
    sa.PrimaryKeyConstraint('template_id', 'subservice_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template_subservices')
    # ### end Alembic commands ###