"""add token blacklist table

Revision ID: 406f0a14d414
Revises: 6984ddf92818
Create Date: 2025-05-22 04:45:16.570146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406f0a14d414'
down_revision = '6984ddf92818'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###