"""Implementación de campos para auditoria y notificaciones

Revision ID: 429801668f8f
Revises: f76374452153
Create Date: 2025-05-20 03:09:19.968264

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '429801668f8f'
down_revision = 'f76374452153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_triggers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('notify_roles', sa.JSON(), nullable=True),
    sa.Column('notify_departments', sa.JSON(), nullable=True),
    sa.Column('notify_entity_owner', sa.Boolean(), nullable=True),
    sa.Column('notify_entity_assignee', sa.Boolean(), nullable=True),
    sa.Column('notification_template', sa.String(length=100), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_triggers')),
    sa.UniqueConstraint('entity_type', 'action', name='uix_notification_entity_action')
    )
    with op.batch_alter_table('notification_triggers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_triggers_id'), ['id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('audit_log_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audit_log_id'], ['audit_logs.id'], name=op.f('fk_notifications_audit_log_id_audit_logs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('idx_notification_importance', ['importance'], unique=False)
        batch_op.create_index('idx_notification_read', ['is_read'], unique=False)
        batch_op.create_index('idx_notification_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_attachments_updated_by_id_users'), 'users', ['updated_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_attachments_created_by_id_users'), 'users', ['created_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_attachments_deleted_by_id_users'), 'users', ['deleted_by_id'], ['id'])

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignee_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('action_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('visibility', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('importance', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('related_users', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('batch_id', sa.String(length=50), nullable=True))
        batch_op.create_index('idx_audit_log_batch', ['batch_id'], unique=False)
        batch_op.create_index('idx_audit_log_category', ['category'], unique=False)
        batch_op.create_index('idx_audit_log_department', ['department_id'], unique=False)
        batch_op.create_index('idx_audit_log_importance', ['importance'], unique=False)
        batch_op.create_index('idx_audit_log_task_assignment', ['entity_type', 'action_type', 'assignee_id'], unique=False)
        batch_op.create_index('idx_audit_log_task_status', ['entity_type', 'action_type'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_audit_logs_department_id_departments'), 'departments', ['department_id'], ['id'])

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_comments_deleted_by_id_users'), 'users', ['deleted_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_comments_updated_by_id_users'), 'users', ['updated_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_comments_created_by_id_users'), 'users', ['created_by_id'], ['id'])

    with op.batch_alter_table('course_classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_course_classes_deleted_by_id_users'), 'users', ['deleted_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_course_classes_created_by_id_users'), 'users', ['created_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_course_classes_updated_by_id_users'), 'users', ['updated_by_id'], ['id'])

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_courses_created_by_id_users'), 'users', ['created_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_courses_updated_by_id_users'), 'users', ['updated_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_courses_deleted_by_id_users'), 'users', ['deleted_by_id'], ['id'])

    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_links_updated_by_id_users'), 'users', ['updated_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_links_created_by_id_users'), 'users', ['created_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_links_deleted_by_id_users'), 'users', ['deleted_by_id'], ['id'])

    with op.batch_alter_table('podcast_episodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_podcast_episodes_deleted_by_id_users'), 'users', ['deleted_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_podcast_episodes_updated_by_id_users'), 'users', ['updated_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_podcast_episodes_created_by_id_users'), 'users', ['created_by_id'], ['id'])

    with op.batch_alter_table('podcast_series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_podcast_series_deleted_by_id_users'), 'users', ['deleted_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_podcast_series_updated_by_id_users'), 'users', ['updated_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_podcast_series_created_by_id_users'), 'users', ['created_by_id'], ['id'])

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_projects_updated_by_id_users'), 'users', ['updated_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_projects_created_by_id_users'), 'users', ['created_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_projects_deleted_by_id_users'), 'users', ['deleted_by_id'], ['id'])

    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_requests_updated_by_id_users'), 'users', ['updated_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_requests_deleted_by_id_users'), 'users', ['deleted_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_requests_created_by_id_users'), 'users', ['created_by_id'], ['id'])

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_tasks_priority_id_priorities', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tasks_deleted_by_id_users'), 'users', ['deleted_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_tasks_created_by_id_users'), 'users', ['created_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_tasks_updated_by_id_users'), 'users', ['updated_by_id'], ['id'])
        batch_op.drop_column('priority_id')

    with op.batch_alter_table('work_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_work_items_created_by_id_users'), 'users', ['created_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_work_items_deleted_by_id_users'), 'users', ['deleted_by_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_work_items_updated_by_id_users'), 'users', ['updated_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_work_items_updated_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_work_items_deleted_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_work_items_created_by_id_users'), type_='foreignkey')
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('deleted_by_id')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_tasks_updated_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_tasks_created_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_tasks_deleted_by_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_tasks_priority_id_priorities', 'priorities', ['priority_id'], ['id'])
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('deleted_by_id')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_requests_created_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_requests_deleted_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_requests_updated_by_id_users'), type_='foreignkey')
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('deleted_by_id')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_projects_deleted_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_projects_created_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_projects_updated_by_id_users'), type_='foreignkey')
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('deleted_by_id')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('podcast_series', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_podcast_series_created_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_podcast_series_updated_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_podcast_series_deleted_by_id_users'), type_='foreignkey')
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('deleted_by_id')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('podcast_episodes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_podcast_episodes_created_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_podcast_episodes_updated_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_podcast_episodes_deleted_by_id_users'), type_='foreignkey')
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('deleted_by_id')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_links_deleted_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_links_created_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_links_updated_by_id_users'), type_='foreignkey')
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('deleted_by_id')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_courses_deleted_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_courses_updated_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_courses_created_by_id_users'), type_='foreignkey')
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('deleted_by_id')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('course_classes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_course_classes_updated_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_course_classes_created_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_course_classes_deleted_by_id_users'), type_='foreignkey')
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('deleted_by_id')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comments_created_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_comments_updated_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_comments_deleted_by_id_users'), type_='foreignkey')
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('deleted_by_id')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_audit_logs_department_id_departments'), type_='foreignkey')
        batch_op.drop_index('idx_audit_log_task_status')
        batch_op.drop_index('idx_audit_log_task_assignment')
        batch_op.drop_index('idx_audit_log_importance')
        batch_op.drop_index('idx_audit_log_department')
        batch_op.drop_index('idx_audit_log_category')
        batch_op.drop_index('idx_audit_log_batch')
        batch_op.drop_column('batch_id')
        batch_op.drop_column('related_users')
        batch_op.drop_column('department_id')
        batch_op.drop_column('importance')
        batch_op.drop_column('visibility')
        batch_op.drop_column('category')
        batch_op.drop_column('action_type')
        batch_op.drop_column('assignee_id')

    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_attachments_deleted_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_attachments_created_by_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_attachments_updated_by_id_users'), type_='foreignkey')
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('deleted_by_id')
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_id'))
        batch_op.drop_index('idx_notification_user')
        batch_op.drop_index('idx_notification_read')
        batch_op.drop_index('idx_notification_importance')

    op.drop_table('notifications')
    with op.batch_alter_table('notification_triggers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_triggers_id'))

    op.drop_table('notification_triggers')
    # ### end Alembic commands ###