"""Add inventory models

Revision ID: 43bd3bb00901
Revises: 233adf249bdf
Create Date: 2025-06-06 21:05:33.985494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43bd3bb00901'
down_revision = '233adf249bdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('is_operational', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment_states')),
    sa.UniqueConstraint('name', name=op.f('uq_equipment_states_name'))
    )
    with op.batch_alter_table('equipment_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equipment_states_id'), ['id'], unique=False)

    op.create_table('inventory_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_equipment', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_inventory_categories_name'))
    )
    with op.batch_alter_table('inventory_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_categories_id'), ['id'], unique=False)

    op.create_table('inventory_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_external', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_locations')),
    sa.UniqueConstraint('name', name=op.f('uq_inventory_locations_name'))
    )
    with op.batch_alter_table('inventory_locations', schema=None) as batch_op:
        batch_op.create_index('idx_inventory_location_active', ['is_active'], unique=False)
        batch_op.create_index('idx_inventory_location_external', ['is_external'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_locations_id'), ['id'], unique=False)

    op.create_table('movement_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('affects_stock', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movement_types')),
    sa.UniqueConstraint('name', name=op.f('uq_movement_types_name'))
    )
    with op.batch_alter_table('movement_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movement_types_id'), ['id'], unique=False)

    op.create_table('component_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_asignada', sa.Integer(), nullable=False),
    sa.Column('fecha_asignacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['inventory_categories.id'], name=op.f('fk_component_assignments_category_id_inventory_categories')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_component_assignments_created_by_id_users')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_component_assignments_updated_by_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_component_assignments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_component_assignments')),
    sa.UniqueConstraint('user_id', 'category_id', name='uix_user_category_assignment')
    )
    with op.batch_alter_table('component_assignments', schema=None) as batch_op:
        batch_op.create_index('idx_component_assignment_category', ['category_id'], unique=False)
        batch_op.create_index('idx_component_assignment_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_component_assignments_id'), ['id'], unique=False)

    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_suppliers_created_by_id_users')),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], name=op.f('fk_suppliers_deleted_by_id_users')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_suppliers_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers')),
    sa.UniqueConstraint('name', name=op.f('uq_suppliers_name'))
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index('idx_supplier_active', ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_id'), ['id'], unique=False)

    op.create_table('supplies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=True),
    sa.Column('nombre_producto', sa.String(length=255), nullable=False),
    sa.Column('presentacion', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('stock_actual', sa.Integer(), nullable=True),
    sa.Column('stock_minimo', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['inventory_categories.id'], name=op.f('fk_supplies_category_id_inventory_categories')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_supplies_created_by_id_users')),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], name=op.f('fk_supplies_deleted_by_id_users')),
    sa.ForeignKeyConstraint(['location_id'], ['inventory_locations.id'], name=op.f('fk_supplies_location_id_inventory_locations')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_supplies_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supplies')),
    sa.UniqueConstraint('codigo', name=op.f('uq_supplies_codigo'))
    )
    with op.batch_alter_table('supplies', schema=None) as batch_op:
        batch_op.create_index('idx_supply_active', ['is_active'], unique=False)
        batch_op.create_index('idx_supply_category', ['category_id'], unique=False)
        batch_op.create_index('idx_supply_codigo', ['codigo'], unique=False)
        batch_op.create_index('idx_supply_location', ['location_id'], unique=False)
        batch_op.create_index('idx_supply_stock_minimo', ['stock_minimo'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplies_id'), ['id'], unique=False)

    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('codigo_ug', sa.String(length=100), nullable=True),
    sa.Column('numero_serie', sa.String(length=255), nullable=True),
    sa.Column('service_tag', sa.String(length=255), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('state_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('fecha_entrega', sa.DateTime(), nullable=True),
    sa.Column('numero_hoja_envio', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], name=op.f('fk_equipment_assigned_user_id_users')),
    sa.ForeignKeyConstraint(['category_id'], ['inventory_categories.id'], name=op.f('fk_equipment_category_id_inventory_categories')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_equipment_created_by_id_users')),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], name=op.f('fk_equipment_deleted_by_id_users')),
    sa.ForeignKeyConstraint(['location_id'], ['inventory_locations.id'], name=op.f('fk_equipment_location_id_inventory_locations')),
    sa.ForeignKeyConstraint(['state_id'], ['equipment_states.id'], name=op.f('fk_equipment_state_id_equipment_states')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_equipment_supplier_id_suppliers')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_equipment_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment'))
    )
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.create_index('idx_equipment_assigned_user', ['assigned_user_id'], unique=False)
        batch_op.create_index('idx_equipment_category', ['category_id'], unique=False)
        batch_op.create_index('idx_equipment_codigo_ug', ['codigo_ug'], unique=False)
        batch_op.create_index('idx_equipment_location', ['location_id'], unique=False)
        batch_op.create_index('idx_equipment_service_tag', ['service_tag'], unique=False)
        batch_op.create_index('idx_equipment_state', ['state_id'], unique=False)
        batch_op.create_index('idx_equipment_supplier', ['supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_id'), ['id'], unique=False)

    op.create_table('supply_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supply_id', sa.Integer(), nullable=False),
    sa.Column('movement_type_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('numero_envio', sa.String(length=100), nullable=True),
    sa.Column('fecha_movimiento', sa.DateTime(), nullable=False),
    sa.Column('user_receives_id', sa.Integer(), nullable=True),
    sa.Column('user_delivers_to_id', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_supply_movements_created_by_id_users')),
    sa.ForeignKeyConstraint(['movement_type_id'], ['movement_types.id'], name=op.f('fk_supply_movements_movement_type_id_movement_types')),
    sa.ForeignKeyConstraint(['supply_id'], ['supplies.id'], name=op.f('fk_supply_movements_supply_id_supplies')),
    sa.ForeignKeyConstraint(['user_delivers_to_id'], ['users.id'], name=op.f('fk_supply_movements_user_delivers_to_id_users')),
    sa.ForeignKeyConstraint(['user_receives_id'], ['users.id'], name=op.f('fk_supply_movements_user_receives_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supply_movements'))
    )
    with op.batch_alter_table('supply_movements', schema=None) as batch_op:
        batch_op.create_index('idx_supply_movement_date', ['fecha_movimiento'], unique=False)
        batch_op.create_index('idx_supply_movement_delivers', ['user_delivers_to_id'], unique=False)
        batch_op.create_index('idx_supply_movement_receives', ['user_receives_id'], unique=False)
        batch_op.create_index('idx_supply_movement_supply', ['supply_id'], unique=False)
        batch_op.create_index('idx_supply_movement_type', ['movement_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supply_movements_id'), ['id'], unique=False)

    op.create_table('equipment_lab',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('numero_pc', sa.String(length=50), nullable=True),
    sa.Column('procesador', sa.String(length=255), nullable=True),
    sa.Column('memoria_ram', sa.String(length=100), nullable=True),
    sa.Column('capacidad_hdd', sa.String(length=100), nullable=True),
    sa.Column('monitor_serie', sa.String(length=255), nullable=True),
    sa.Column('monitor_codigo_ug', sa.String(length=100), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('fecha_recepcion_sega', sa.DateTime(), nullable=True),
    sa.Column('fecha_entrega_medialab', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_equipment_lab_created_by_id_users')),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], name=op.f('fk_equipment_lab_deleted_by_id_users')),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name=op.f('fk_equipment_lab_equipment_id_equipment')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_equipment_lab_supplier_id_suppliers')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_equipment_lab_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipment_lab')),
    sa.UniqueConstraint('equipment_id', name=op.f('uq_equipment_lab_equipment_id'))
    )
    with op.batch_alter_table('equipment_lab', schema=None) as batch_op:
        batch_op.create_index('idx_equipment_lab_equipment', ['equipment_id'], unique=False)
        batch_op.create_index('idx_equipment_lab_numero_pc', ['numero_pc'], unique=False)
        batch_op.create_index('idx_equipment_lab_supplier', ['supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_equipment_lab_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_lab', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_lab_id'))
        batch_op.drop_index('idx_equipment_lab_supplier')
        batch_op.drop_index('idx_equipment_lab_numero_pc')
        batch_op.drop_index('idx_equipment_lab_equipment')

    op.drop_table('equipment_lab')
    with op.batch_alter_table('supply_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supply_movements_id'))
        batch_op.drop_index('idx_supply_movement_type')
        batch_op.drop_index('idx_supply_movement_supply')
        batch_op.drop_index('idx_supply_movement_receives')
        batch_op.drop_index('idx_supply_movement_delivers')
        batch_op.drop_index('idx_supply_movement_date')

    op.drop_table('supply_movements')
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_id'))
        batch_op.drop_index('idx_equipment_supplier')
        batch_op.drop_index('idx_equipment_state')
        batch_op.drop_index('idx_equipment_service_tag')
        batch_op.drop_index('idx_equipment_location')
        batch_op.drop_index('idx_equipment_codigo_ug')
        batch_op.drop_index('idx_equipment_category')
        batch_op.drop_index('idx_equipment_assigned_user')

    op.drop_table('equipment')
    with op.batch_alter_table('supplies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplies_id'))
        batch_op.drop_index('idx_supply_stock_minimo')
        batch_op.drop_index('idx_supply_location')
        batch_op.drop_index('idx_supply_codigo')
        batch_op.drop_index('idx_supply_category')
        batch_op.drop_index('idx_supply_active')

    op.drop_table('supplies')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_id'))
        batch_op.drop_index('idx_supplier_active')

    op.drop_table('suppliers')
    with op.batch_alter_table('component_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_component_assignments_id'))
        batch_op.drop_index('idx_component_assignment_user')
        batch_op.drop_index('idx_component_assignment_category')

    op.drop_table('component_assignments')
    with op.batch_alter_table('movement_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movement_types_id'))

    op.drop_table('movement_types')
    with op.batch_alter_table('inventory_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_locations_id'))
        batch_op.drop_index('idx_inventory_location_external')
        batch_op.drop_index('idx_inventory_location_active')

    op.drop_table('inventory_locations')
    with op.batch_alter_table('inventory_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_categories_id'))

    op.drop_table('inventory_categories')
    with op.batch_alter_table('equipment_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipment_states_id'))

    op.drop_table('equipment_states')
    # ### end Alembic commands ###