"""Implementacion modelo de usuario institucional

Revision ID: 43f0ce3aff2c
Revises: b95f734f4816
Create Date: 2025-05-19 20:09:49.035413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43f0ce3aff2c'
down_revision = 'b95f734f4816'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutional_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_institutional_users_department_id_departments')),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], name=op.f('fk_institutional_users_faculty_id_faculties')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_institutional_users')),
    sa.UniqueConstraint('email', name=op.f('uq_institutional_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_institutional_users_username'))
    )
    with op.batch_alter_table('institutional_users', schema=None) as batch_op:
        batch_op.create_index('idx_institutional_user_department', ['department_id'], unique=False)
        batch_op.create_index('idx_institutional_user_email', ['email'], unique=False)
        batch_op.create_index('idx_institutional_user_faculty', ['faculty_id'], unique=False)
        batch_op.create_index('idx_institutional_user_is_active', ['is_active'], unique=False)
        batch_op.create_index('idx_institutional_user_username', ['username'], unique=False)
        batch_op.create_index(batch_op.f('ix_institutional_users_id'), ['id'], unique=False)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institutional_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_comments_institutional_user_id_institutional_users'), 'institutional_users', ['institutional_user_id'], ['id'])

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institutional_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_courses_institutional_user_id_institutional_users'), 'institutional_users', ['institutional_user_id'], ['id'])

    with op.batch_alter_table('podcast_series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institutional_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_podcast_series_institutional_user_id_institutional_users'), 'institutional_users', ['institutional_user_id'], ['id'])

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institutional_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_projects_institutional_user_id_institutional_users'), 'institutional_users', ['institutional_user_id'], ['id'])

    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requester_institutional_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_requests_requester_institutional_id_institutional_users'), 'institutional_users', ['requester_institutional_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_requests_requester_institutional_id_institutional_users'), type_='foreignkey')
        batch_op.drop_column('requester_institutional_id')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_projects_institutional_user_id_institutional_users'), type_='foreignkey')
        batch_op.drop_column('institutional_user_id')

    with op.batch_alter_table('podcast_series', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_podcast_series_institutional_user_id_institutional_users'), type_='foreignkey')
        batch_op.drop_column('institutional_user_id')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_courses_institutional_user_id_institutional_users'), type_='foreignkey')
        batch_op.drop_column('institutional_user_id')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comments_institutional_user_id_institutional_users'), type_='foreignkey')
        batch_op.drop_column('institutional_user_id')

    with op.batch_alter_table('institutional_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_institutional_users_id'))
        batch_op.drop_index('idx_institutional_user_username')
        batch_op.drop_index('idx_institutional_user_is_active')
        batch_op.drop_index('idx_institutional_user_faculty')
        batch_op.drop_index('idx_institutional_user_email')
        batch_op.drop_index('idx_institutional_user_department')

    op.drop_table('institutional_users')
    # ### end Alembic commands ###