"""initial migration

Revision ID: 6984ddf92818
Revises: 
Create Date: 2025-05-20 19:19:21.908452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6984ddf92818'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_academic_periods')),
    sa.UniqueConstraint('code', name=op.f('uq_academic_periods_code'))
    )
    with op.batch_alter_table('academic_periods', schema=None) as batch_op:
        batch_op.create_index('idx_academic_period_active', ['is_active'], unique=False)
        batch_op.create_index('idx_academic_period_code', ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_academic_periods_id'), ['id'], unique=False)

    op.create_table('activity_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_types')),
    sa.UniqueConstraint('name', name=op.f('uq_activity_types_name'))
    )
    with op.batch_alter_table('activity_types', schema=None) as batch_op:
        batch_op.create_index('idx_activity_type_category', ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_types_id'), ['id'], unique=False)

    op.create_table('areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_areas')),
    sa.UniqueConstraint('name', name=op.f('uq_areas_name'))
    )
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_areas_id'), ['id'], unique=False)

    op.create_table('department_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_department_types')),
    sa.UniqueConstraint('name', name=op.f('uq_department_types_name'))
    )
    with op.batch_alter_table('department_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_department_types_id'), ['id'], unique=False)

    op.create_table('email_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('available_variables', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_templates')),
    sa.UniqueConstraint('code', name=op.f('uq_email_templates_code'))
    )
    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_templates_id'), ['id'], unique=False)

    op.create_table('notification_triggers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('notify_roles', sa.JSON(), nullable=True),
    sa.Column('notify_departments', sa.JSON(), nullable=True),
    sa.Column('notify_entity_owner', sa.Boolean(), nullable=True),
    sa.Column('notify_entity_assignee', sa.Boolean(), nullable=True),
    sa.Column('notification_template', sa.String(length=100), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_triggers')),
    sa.UniqueConstraint('entity_type', 'action', name='uix_notification_entity_action')
    )
    with op.batch_alter_table('notification_triggers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_triggers_id'), ['id'], unique=False)

    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('name', name=op.f('uq_permissions_name'))
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permissions_id'), ['id'], unique=False)

    op.create_table('platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('url_base', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('supports_video', sa.Boolean(), nullable=True),
    sa.Column('supports_audio', sa.Boolean(), nullable=True),
    sa.Column('supports_documents', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platforms')),
    sa.UniqueConstraint('name', name=op.f('uq_platforms_name'))
    )
    with op.batch_alter_table('platforms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platforms_id'), ['id'], unique=False)

    op.create_table('priorities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_priorities')),
    sa.UniqueConstraint('name', name=op.f('uq_priorities_name'))
    )
    with op.batch_alter_table('priorities', schema=None) as batch_op:
        batch_op.create_index('idx_priority_order', ['order'], unique=False)
        batch_op.create_index(batch_op.f('ix_priorities_id'), ['id'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_id'), ['id'], unique=False)

    op.create_table('service_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_templates')),
    sa.UniqueConstraint('name', name=op.f('uq_service_templates_name'))
    )
    with op.batch_alter_table('service_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_templates_id'), ['id'], unique=False)

    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon_name', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services')),
    sa.UniqueConstraint('name', name=op.f('uq_services_name'))
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_id'), ['id'], unique=False)

    op.create_table('smtp_configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('use_tls', sa.Boolean(), nullable=True),
    sa.Column('use_ssl', sa.Boolean(), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=True),
    sa.Column('default_from_name', sa.String(length=100), nullable=False),
    sa.Column('default_from_email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_smtp_configuration'))
    )
    with op.batch_alter_table('smtp_configuration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_smtp_configuration_id'), ['id'], unique=False)

    op.create_table('statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_initial', sa.Boolean(), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statuses')),
    sa.UniqueConstraint('name', 'entity_type', name='uix_status_name_entity')
    )
    with op.batch_alter_table('statuses', schema=None) as batch_op:
        batch_op.create_index('idx_status_entity_type', ['entity_type'], unique=False)
        batch_op.create_index('idx_status_level', ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_statuses_id'), ['id'], unique=False)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('name', name=op.f('uq_tags_name'))
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_id'), ['id'], unique=False)

    op.create_table('two_factor_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_two_factor_methods')),
    sa.UniqueConstraint('code', name=op.f('uq_two_factor_methods_code'))
    )
    with op.batch_alter_table('two_factor_methods', schema=None) as batch_op:
        batch_op.create_index('idx_2fa_method_active', ['is_active'], unique=False)
        batch_op.create_index('idx_2fa_method_code', ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_two_factor_methods_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('banner_image', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('join_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_user_is_active', ['is_active'], unique=False)
        batch_op.create_index('idx_user_join_date', ['join_date'], unique=False)
        batch_op.create_index('idx_user_last_login', ['last_login'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_attachments_created_by_id_users')),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], name=op.f('fk_attachments_deleted_by_id_users')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_attachments_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments'))
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index('idx_attachments_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('idx_attachments_mime', ['mime_type'], unique=False)
        batch_op.create_index('idx_attachments_uploader', ['uploaded_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_id'), ['id'], unique=False)

    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('abbreviation', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['department_types.id'], name=op.f('fk_departments_type_id_department_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('abbreviation', name=op.f('uq_departments_abbreviation')),
    sa.UniqueConstraint('name', name=op.f('uq_departments_name'))
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_id'), ['id'], unique=False)

    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_links_created_by_id_users')),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], name=op.f('fk_links_deleted_by_id_users')),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], name=op.f('fk_links_platform_id_platforms')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_links_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_links'))
    )
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.create_index('idx_links_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('idx_links_platform', ['platform_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_links_id'), ['id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles')),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.create_index('idx_role_permissions_permission', ['permission_id'], unique=False)
        batch_op.create_index('idx_role_permissions_role', ['role_id'], unique=False)

    op.create_table('status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('old_status_id', sa.Integer(), nullable=True),
    sa.Column('new_status_id', sa.Integer(), nullable=False),
    sa.Column('old_level', sa.Integer(), nullable=True),
    sa.Column('new_level', sa.Integer(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('change_date', sa.DateTime(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['new_status_id'], ['statuses.id'], name=op.f('fk_status_history_new_status_id_statuses')),
    sa.ForeignKeyConstraint(['old_status_id'], ['statuses.id'], name=op.f('fk_status_history_old_status_id_statuses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_status_history'))
    )
    with op.batch_alter_table('status_history', schema=None) as batch_op:
        batch_op.create_index('idx_status_history_date', ['change_date'], unique=False)
        batch_op.create_index('idx_status_history_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('idx_status_history_user', ['changed_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_status_history_id'), ['id'], unique=False)

    op.create_table('sub_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_sub_services_service_id_services')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sub_services'))
    )
    with op.batch_alter_table('sub_services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sub_services_id'), ['id'], unique=False)

    op.create_table('tag_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_tag_assignments_tag_id_tags')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tag_assignments')),
    sa.UniqueConstraint('tag_id', 'entity_id', 'entity_type', name='uix_tag_entity')
    )
    with op.batch_alter_table('tag_assignments', schema=None) as batch_op:
        batch_op.create_index('idx_tag_assignment_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('idx_tag_assignment_tag', ['tag_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tag_assignments_id'), ['id'], unique=False)

    op.create_table('template_services',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_template_services_service_id_services')),
    sa.ForeignKeyConstraint(['template_id'], ['service_templates.id'], name=op.f('fk_template_services_template_id_service_templates')),
    sa.PrimaryKeyConstraint('template_id', 'service_id', name=op.f('pk_template_services'))
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], name=op.f('fk_user_roles_area_id_areas')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_roles')),
    sa.UniqueConstraint('user_id', 'role_id', 'area_id', name='uix_user_role_area')
    )
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_index('idx_user_roles_area', ['area_id'], unique=False)
        batch_op.create_index('idx_user_roles_role', ['role_id'], unique=False)
        batch_op.create_index('idx_user_roles_user', ['user_id'], unique=False)

    op.create_table('user_two_factor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('method_id', sa.Integer(), nullable=False),
    sa.Column('secret_key', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('backup_codes', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['method_id'], ['two_factor_methods.id'], name=op.f('fk_user_two_factor_method_id_two_factor_methods')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_two_factor')),
    sa.UniqueConstraint('user_id', 'method_id', name='uix_user_2fa_method')
    )
    with op.batch_alter_table('user_two_factor', schema=None) as batch_op:
        batch_op.create_index('idx_user_2fa_enabled', ['is_enabled'], unique=False)
        batch_op.create_index('idx_user_2fa_method', ['method_id'], unique=False)
        batch_op.create_index('idx_user_2fa_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_two_factor_id'), ['id'], unique=False)

    op.create_table('work_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('priority_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.Column('deliverable_url', sa.String(length=255), nullable=True),
    sa.Column('has_deliverable', sa.Boolean(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_work_items_created_by_id_users')),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], name=op.f('fk_work_items_deleted_by_id_users')),
    sa.ForeignKeyConstraint(['priority_id'], ['priorities.id'], name=op.f('fk_work_items_priority_id_priorities')),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], name=op.f('fk_work_items_status_id_statuses')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_work_items_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_items'))
    )
    with op.batch_alter_table('work_items', schema=None) as batch_op:
        batch_op.create_index('idx_work_item_entity_type', ['entity_type'], unique=False)
        batch_op.create_index('idx_work_item_priority', ['priority_id'], unique=False)
        batch_op.create_index('idx_work_item_status', ['status_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_items_id'), ['id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('related_users', sa.JSON(), nullable=True),
    sa.Column('batch_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_audit_logs_department_id_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_log_action', ['action'], unique=False)
        batch_op.create_index('idx_audit_log_batch', ['batch_id'], unique=False)
        batch_op.create_index('idx_audit_log_category', ['category'], unique=False)
        batch_op.create_index('idx_audit_log_department', ['department_id'], unique=False)
        batch_op.create_index('idx_audit_log_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index('idx_audit_log_importance', ['importance'], unique=False)
        batch_op.create_index('idx_audit_log_task_assignment', ['entity_type', 'action_type', 'assignee_id'], unique=False)
        batch_op.create_index('idx_audit_log_task_status', ['entity_type', 'action_type'], unique=False)
        batch_op.create_index('idx_audit_log_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('idx_audit_log_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    op.create_table('careers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('academic_period_id', sa.Integer(), nullable=True),
    sa.Column('is_active_in_period', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['academic_period_id'], ['academic_periods.id'], name=op.f('fk_careers_academic_period_id_academic_periods')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_careers_department_id_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_careers')),
    sa.UniqueConstraint('name', 'department_id', name='uix_career_name_department')
    )
    with op.batch_alter_table('careers', schema=None) as batch_op:
        batch_op.create_index('idx_career_code', ['code'], unique=False)
        batch_op.create_index('idx_career_department', ['department_id'], unique=False)
        batch_op.create_index('idx_career_period', ['academic_period_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_careers_id'), ['id'], unique=False)

    op.create_table('institutional_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('reset_token', sa.String(length=255), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_institutional_users_department_id_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_institutional_users')),
    sa.UniqueConstraint('email', name=op.f('uq_institutional_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_institutional_users_username'))
    )
    with op.batch_alter_table('institutional_users', schema=None) as batch_op:
        batch_op.create_index('idx_institutional_user_department', ['department_id'], unique=False)
        batch_op.create_index('idx_institutional_user_email', ['email'], unique=False)
        batch_op.create_index('idx_institutional_user_is_active', ['is_active'], unique=False)
        batch_op.create_index('idx_institutional_user_username', ['username'], unique=False)
        batch_op.create_index(batch_op.f('ix_institutional_users_id'), ['id'], unique=False)

    op.create_table('professors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_professors_department_id_departments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_professors'))
    )
    with op.batch_alter_table('professors', schema=None) as batch_op:
        batch_op.create_index('idx_professor_department', ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_professors_id'), ['id'], unique=False)

    op.create_table('template_subservices',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('subservice_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subservice_id'], ['sub_services.id'], name=op.f('fk_template_subservices_subservice_id_sub_services')),
    sa.ForeignKeyConstraint(['template_id'], ['service_templates.id'], name=op.f('fk_template_subservices_template_id_service_templates')),
    sa.PrimaryKeyConstraint('template_id', 'subservice_id', name=op.f('pk_template_subservices'))
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('is_client_comment', sa.Boolean(), nullable=True),
    sa.Column('institutional_user_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_comments_created_by_id_users')),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], name=op.f('fk_comments_deleted_by_id_users')),
    sa.ForeignKeyConstraint(['institutional_user_id'], ['institutional_users.id'], name=op.f('fk_comments_institutional_user_id_institutional_users')),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], name=op.f('fk_comments_parent_id_comments')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_comments_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index('idx_comments_author', ['author_id'], unique=False)
        batch_op.create_index('idx_comments_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_id'), ['id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('audit_log_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audit_log_id'], ['audit_logs.id'], name=op.f('fk_notifications_audit_log_id_audit_logs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('idx_notification_importance', ['importance'], unique=False)
        batch_op.create_index('idx_notification_read', ['is_read'], unique=False)
        batch_op.create_index('idx_notification_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_id'), ['id'], unique=False)

    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('contact_info', sa.JSON(), nullable=True),
    sa.Column('request_date', sa.Date(), nullable=False),
    sa.Column('desired_date', sa.DateTime(), nullable=True),
    sa.Column('location_type', sa.String(length=50), nullable=True),
    sa.Column('location_details', sa.JSON(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('processing_notes', sa.Text(), nullable=True),
    sa.Column('requester_institutional_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_requests_department_id_departments')),
    sa.ForeignKeyConstraint(['id'], ['work_items.id'], name=op.f('fk_requests_id_work_items')),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name=op.f('fk_requests_requester_id_users')),
    sa.ForeignKeyConstraint(['requester_institutional_id'], ['institutional_users.id'], name=op.f('fk_requests_requester_institutional_id_institutional_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requests'))
    )
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.create_index('idx_request_activity_type', ['activity_type'], unique=False)
        batch_op.create_index('idx_request_department', ['department_id'], unique=False)
        batch_op.create_index('idx_request_is_processed', ['is_processed'], unique=False)
        batch_op.create_index('idx_request_requester', ['requester_id'], unique=False)

    op.create_table('course_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('career_name', sa.String(length=255), nullable=False),
    sa.Column('course_description', sa.Text(), nullable=True),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('is_recurrent', sa.Boolean(), nullable=True),
    sa.Column('recurrence_type', sa.String(length=50), nullable=True),
    sa.Column('recurrence_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['departments.id'], name=op.f('fk_course_requests_faculty_id_departments')),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('fk_course_requests_request_id_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_requests')),
    sa.UniqueConstraint('request_id', name=op.f('uq_course_requests_request_id'))
    )
    with op.batch_alter_table('course_requests', schema=None) as batch_op:
        batch_op.create_index('idx_course_request_faculty', ['faculty_id'], unique=False)
        batch_op.create_index('idx_course_request_request', ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_requests_id'), ['id'], unique=False)

    op.create_table('podcast_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('podcast_name', sa.String(length=255), nullable=False),
    sa.Column('podcast_description', sa.Text(), nullable=True),
    sa.Column('is_recurrent', sa.Boolean(), nullable=True),
    sa.Column('recurrence_type', sa.String(length=50), nullable=True),
    sa.Column('recurrence_config', sa.JSON(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('fk_podcast_requests_request_id_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_podcast_requests')),
    sa.UniqueConstraint('request_id', name=op.f('uq_podcast_requests_request_id'))
    )
    with op.batch_alter_table('podcast_requests', schema=None) as batch_op:
        batch_op.create_index('idx_podcast_request_request', ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_podcast_requests_id'), ['id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('activity_type_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('is_recurrent', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('institutional_user_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_type_id'], ['activity_types.id'], name=op.f('fk_projects_activity_type_id_activity_types')),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_projects_department_id_departments')),
    sa.ForeignKeyConstraint(['id'], ['work_items.id'], name=op.f('fk_projects_id_work_items')),
    sa.ForeignKeyConstraint(['institutional_user_id'], ['institutional_users.id'], name=op.f('fk_projects_institutional_user_id_institutional_users')),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('fk_projects_request_id_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('code', name=op.f('uq_projects_code'))
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('idx_project_activity_type', ['activity_type_id'], unique=False)
        batch_op.create_index('idx_project_client', ['client_id'], unique=False)
        batch_op.create_index('idx_project_code', ['code'], unique=False)
        batch_op.create_index('idx_project_department', ['department_id'], unique=False)
        batch_op.create_index('idx_project_is_active', ['is_active'], unique=False)
        batch_op.create_index('idx_project_request', ['request_id'], unique=False)

    op.create_table('recurrent_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('recurrence_type', sa.String(length=50), nullable=False),
    sa.Column('recurrence_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('fk_recurrent_events_request_id_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recurrent_events')),
    sa.UniqueConstraint('request_id', name=op.f('uq_recurrent_events_request_id'))
    )
    with op.batch_alter_table('recurrent_events', schema=None) as batch_op:
        batch_op.create_index('idx_recurrent_event_end_date', ['end_date'], unique=False)
        batch_op.create_index('idx_recurrent_event_request', ['request_id'], unique=False)
        batch_op.create_index('idx_recurrent_event_start_date', ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurrent_events_id'), ['id'], unique=False)

    op.create_table('request_services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('fk_request_services_request_id_requests')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_request_services_service_id_services')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request_services')),
    sa.UniqueConstraint('request_id', 'service_id', name='uix_request_service')
    )
    with op.batch_alter_table('request_services', schema=None) as batch_op:
        batch_op.create_index('idx_request_services_request', ['request_id'], unique=False)
        batch_op.create_index('idx_request_services_service', ['service_id'], unique=False)

    op.create_table('request_sub_services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('sub_service_id', sa.Integer(), nullable=False),
    sa.Column('main_service_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['main_service_id'], ['services.id'], name=op.f('fk_request_sub_services_main_service_id_services')),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('fk_request_sub_services_request_id_requests')),
    sa.ForeignKeyConstraint(['sub_service_id'], ['sub_services.id'], name=op.f('fk_request_sub_services_sub_service_id_sub_services')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request_sub_services')),
    sa.UniqueConstraint('request_id', 'sub_service_id', name='uix_request_subservice')
    )
    with op.batch_alter_table('request_sub_services', schema=None) as batch_op:
        batch_op.create_index('idx_request_sub_services_mainservice', ['main_service_id'], unique=False)
        batch_op.create_index('idx_request_sub_services_request', ['request_id'], unique=False)
        batch_op.create_index('idx_request_sub_services_subservice', ['sub_service_id'], unique=False)

    op.create_table('single_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], name=op.f('fk_single_events_request_id_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_single_events')),
    sa.UniqueConstraint('request_id', name=op.f('uq_single_events_request_id'))
    )
    with op.batch_alter_table('single_events', schema=None) as batch_op:
        batch_op.create_index('idx_single_event_date', ['event_date'], unique=False)
        batch_op.create_index('idx_single_event_request', ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_single_events_id'), ['id'], unique=False)

    op.create_table('course_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_request_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.Column('professor_name', sa.String(length=255), nullable=True),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_request_id'], ['course_requests.id'], name=op.f('fk_course_items_course_request_id_course_requests')),
    sa.ForeignKeyConstraint(['faculty_id'], ['departments.id'], name=op.f('fk_course_items_faculty_id_departments')),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id'], name=op.f('fk_course_items_professor_id_professors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_items'))
    )
    with op.batch_alter_table('course_items', schema=None) as batch_op:
        batch_op.create_index('idx_course_item_faculty', ['faculty_id'], unique=False)
        batch_op.create_index('idx_course_item_professor', ['professor_id'], unique=False)
        batch_op.create_index('idx_course_item_request', ['course_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_items_id'), ['id'], unique=False)

    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('career_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('course_request_id', sa.Integer(), nullable=True),
    sa.Column('institutional_user_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], name=op.f('fk_courses_career_id_careers')),
    sa.ForeignKeyConstraint(['course_request_id'], ['course_requests.id'], name=op.f('fk_courses_course_request_id_course_requests')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_courses_created_by_id_users')),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], name=op.f('fk_courses_deleted_by_id_users')),
    sa.ForeignKeyConstraint(['institutional_user_id'], ['institutional_users.id'], name=op.f('fk_courses_institutional_user_id_institutional_users')),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], name=op.f('fk_courses_status_id_statuses')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_courses_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses')),
    sa.UniqueConstraint('code', 'career_id', name='uix_course_code_career')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index('idx_course_career', ['career_id'], unique=False)
        batch_op.create_index('idx_course_institutional_user', ['institutional_user_id'], unique=False)
        batch_op.create_index('idx_course_is_active', ['is_active'], unique=False)
        batch_op.create_index('idx_course_request', ['course_request_id'], unique=False)
        batch_op.create_index('idx_course_status', ['status_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_id'), ['id'], unique=False)

    op.create_table('event_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recurrent_event_id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recurrent_event_id'], ['recurrent_events.id'], name=op.f('fk_event_dates_recurrent_event_id_recurrent_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_dates')),
    sa.UniqueConstraint('recurrent_event_id', 'event_date', name='uix_event_date')
    )
    with op.batch_alter_table('event_dates', schema=None) as batch_op:
        batch_op.create_index('idx_event_dates_date', ['event_date'], unique=False)
        batch_op.create_index('idx_event_dates_event', ['recurrent_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_dates_id'), ['id'], unique=False)

    op.create_table('podcast_moderators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('podcast_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['podcast_id'], ['podcast_requests.id'], name=op.f('fk_podcast_moderators_podcast_id_podcast_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_podcast_moderators'))
    )
    with op.batch_alter_table('podcast_moderators', schema=None) as batch_op:
        batch_op.create_index('idx_podcast_moderator_podcast', ['podcast_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_podcast_moderators_id'), ['id'], unique=False)

    op.create_table('podcast_request_episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('podcast_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('fk_podcast_request_episodes_department_id_departments')),
    sa.ForeignKeyConstraint(['podcast_id'], ['podcast_requests.id'], name=op.f('fk_podcast_request_episodes_podcast_id_podcast_requests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_podcast_request_episodes'))
    )
    with op.batch_alter_table('podcast_request_episodes', schema=None) as batch_op:
        batch_op.create_index('idx_podcast_episode_department', ['department_id'], unique=False)
        batch_op.create_index('idx_podcast_episode_podcast', ['podcast_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_podcast_request_episodes_id'), ['id'], unique=False)

    op.create_table('podcast_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_image_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('main_platform_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('podcast_request_id', sa.Integer(), nullable=True),
    sa.Column('institutional_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_podcast_series_created_by_id_users')),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], name=op.f('fk_podcast_series_deleted_by_id_users')),
    sa.ForeignKeyConstraint(['institutional_user_id'], ['institutional_users.id'], name=op.f('fk_podcast_series_institutional_user_id_institutional_users')),
    sa.ForeignKeyConstraint(['main_platform_id'], ['platforms.id'], name=op.f('fk_podcast_series_main_platform_id_platforms')),
    sa.ForeignKeyConstraint(['podcast_request_id'], ['podcast_requests.id'], name=op.f('fk_podcast_series_podcast_request_id_podcast_requests')),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], name=op.f('fk_podcast_series_status_id_statuses')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_podcast_series_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_podcast_series'))
    )
    with op.batch_alter_table('podcast_series', schema=None) as batch_op:
        batch_op.create_index('idx_podcast_series_platform', ['main_platform_id'], unique=False)
        batch_op.create_index('idx_podcast_series_request', ['podcast_request_id'], unique=False)
        batch_op.create_index('idx_podcast_series_status', ['status_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_podcast_series_id'), ['id'], unique=False)

    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('activity_type_id', sa.Integer(), nullable=True),
    sa.Column('activity_entity_type', sa.String(length=50), nullable=True),
    sa.Column('activity_entity_id', sa.Integer(), nullable=True),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_type_id'], ['activity_types.id'], name=op.f('fk_tasks_activity_type_id_activity_types')),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name=op.f('fk_tasks_assignee_id_users')),
    sa.ForeignKeyConstraint(['id'], ['work_items.id'], name=op.f('fk_tasks_id_work_items')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_tasks_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('idx_task_activity_type', ['activity_type_id'], unique=False)
        batch_op.create_index('idx_task_assignee', ['assignee_id'], unique=False)
        batch_op.create_index('idx_task_project', ['project_id'], unique=False)

    op.create_table('course_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('class_number', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.Column('course_item_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('recording_date', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_classes_course_id_courses')),
    sa.ForeignKeyConstraint(['course_item_id'], ['course_items.id'], name=op.f('fk_course_classes_course_item_id_course_items')),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_course_classes_created_by_id_users')),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], name=op.f('fk_course_classes_deleted_by_id_users')),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id'], name=op.f('fk_course_classes_professor_id_professors')),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], name=op.f('fk_course_classes_status_id_statuses')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_course_classes_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_classes'))
    )
    with op.batch_alter_table('course_classes', schema=None) as batch_op:
        batch_op.create_index('idx_course_class_course', ['course_id'], unique=False)
        batch_op.create_index('idx_course_class_item', ['course_item_id'], unique=False)
        batch_op.create_index('idx_course_class_professor', ['professor_id'], unique=False)
        batch_op.create_index('idx_course_class_scheduled', ['scheduled_date'], unique=False)
        batch_op.create_index('idx_course_class_status', ['status_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_classes_id'), ['id'], unique=False)

    op.create_table('course_recording_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_item_id', sa.Integer(), nullable=False),
    sa.Column('recording_date', sa.Date(), nullable=False),
    sa.Column('recording_time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_item_id'], ['course_items.id'], name=op.f('fk_course_recording_dates_course_item_id_course_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_recording_dates')),
    sa.UniqueConstraint('course_item_id', 'recording_date', name='uix_course_recording_date')
    )
    with op.batch_alter_table('course_recording_dates', schema=None) as batch_op:
        batch_op.create_index('idx_course_recording_dates_course', ['course_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_recording_dates_id'), ['id'], unique=False)

    op.create_table('podcast_episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('recording_date', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('request_episode_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_podcast_episodes_created_by_id_users')),
    sa.ForeignKeyConstraint(['deleted_by_id'], ['users.id'], name=op.f('fk_podcast_episodes_deleted_by_id_users')),
    sa.ForeignKeyConstraint(['request_episode_id'], ['podcast_request_episodes.id'], name=op.f('fk_podcast_episodes_request_episode_id_podcast_request_episodes')),
    sa.ForeignKeyConstraint(['series_id'], ['podcast_series.id'], name=op.f('fk_podcast_episodes_series_id_podcast_series')),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], name=op.f('fk_podcast_episodes_status_id_statuses')),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_podcast_episodes_updated_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_podcast_episodes'))
    )
    with op.batch_alter_table('podcast_episodes', schema=None) as batch_op:
        batch_op.create_index('idx_podcast_episode_request', ['request_episode_id'], unique=False)
        batch_op.create_index('idx_podcast_episode_series', ['series_id'], unique=False)
        batch_op.create_index('idx_podcast_episode_status', ['status_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_podcast_episodes_id'), ['id'], unique=False)

    op.create_table('podcast_guests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['podcast_request_episodes.id'], name=op.f('fk_podcast_guests_episode_id_podcast_request_episodes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_podcast_guests'))
    )
    with op.batch_alter_table('podcast_guests', schema=None) as batch_op:
        batch_op.create_index('idx_podcast_guest_episode', ['episode_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_podcast_guests_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcast_guests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_podcast_guests_id'))
        batch_op.drop_index('idx_podcast_guest_episode')

    op.drop_table('podcast_guests')
    with op.batch_alter_table('podcast_episodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_podcast_episodes_id'))
        batch_op.drop_index('idx_podcast_episode_status')
        batch_op.drop_index('idx_podcast_episode_series')
        batch_op.drop_index('idx_podcast_episode_request')

    op.drop_table('podcast_episodes')
    with op.batch_alter_table('course_recording_dates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_recording_dates_id'))
        batch_op.drop_index('idx_course_recording_dates_course')

    op.drop_table('course_recording_dates')
    with op.batch_alter_table('course_classes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_classes_id'))
        batch_op.drop_index('idx_course_class_status')
        batch_op.drop_index('idx_course_class_scheduled')
        batch_op.drop_index('idx_course_class_professor')
        batch_op.drop_index('idx_course_class_item')
        batch_op.drop_index('idx_course_class_course')

    op.drop_table('course_classes')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('idx_task_project')
        batch_op.drop_index('idx_task_assignee')
        batch_op.drop_index('idx_task_activity_type')

    op.drop_table('tasks')
    with op.batch_alter_table('podcast_series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_podcast_series_id'))
        batch_op.drop_index('idx_podcast_series_status')
        batch_op.drop_index('idx_podcast_series_request')
        batch_op.drop_index('idx_podcast_series_platform')

    op.drop_table('podcast_series')
    with op.batch_alter_table('podcast_request_episodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_podcast_request_episodes_id'))
        batch_op.drop_index('idx_podcast_episode_podcast')
        batch_op.drop_index('idx_podcast_episode_department')

    op.drop_table('podcast_request_episodes')
    with op.batch_alter_table('podcast_moderators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_podcast_moderators_id'))
        batch_op.drop_index('idx_podcast_moderator_podcast')

    op.drop_table('podcast_moderators')
    with op.batch_alter_table('event_dates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_dates_id'))
        batch_op.drop_index('idx_event_dates_event')
        batch_op.drop_index('idx_event_dates_date')

    op.drop_table('event_dates')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_id'))
        batch_op.drop_index('idx_course_status')
        batch_op.drop_index('idx_course_request')
        batch_op.drop_index('idx_course_is_active')
        batch_op.drop_index('idx_course_institutional_user')
        batch_op.drop_index('idx_course_career')

    op.drop_table('courses')
    with op.batch_alter_table('course_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_items_id'))
        batch_op.drop_index('idx_course_item_request')
        batch_op.drop_index('idx_course_item_professor')
        batch_op.drop_index('idx_course_item_faculty')

    op.drop_table('course_items')
    with op.batch_alter_table('single_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_single_events_id'))
        batch_op.drop_index('idx_single_event_request')
        batch_op.drop_index('idx_single_event_date')

    op.drop_table('single_events')
    with op.batch_alter_table('request_sub_services', schema=None) as batch_op:
        batch_op.drop_index('idx_request_sub_services_subservice')
        batch_op.drop_index('idx_request_sub_services_request')
        batch_op.drop_index('idx_request_sub_services_mainservice')

    op.drop_table('request_sub_services')
    with op.batch_alter_table('request_services', schema=None) as batch_op:
        batch_op.drop_index('idx_request_services_service')
        batch_op.drop_index('idx_request_services_request')

    op.drop_table('request_services')
    with op.batch_alter_table('recurrent_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurrent_events_id'))
        batch_op.drop_index('idx_recurrent_event_start_date')
        batch_op.drop_index('idx_recurrent_event_request')
        batch_op.drop_index('idx_recurrent_event_end_date')

    op.drop_table('recurrent_events')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('idx_project_request')
        batch_op.drop_index('idx_project_is_active')
        batch_op.drop_index('idx_project_department')
        batch_op.drop_index('idx_project_code')
        batch_op.drop_index('idx_project_client')
        batch_op.drop_index('idx_project_activity_type')

    op.drop_table('projects')
    with op.batch_alter_table('podcast_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_podcast_requests_id'))
        batch_op.drop_index('idx_podcast_request_request')

    op.drop_table('podcast_requests')
    with op.batch_alter_table('course_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_requests_id'))
        batch_op.drop_index('idx_course_request_request')
        batch_op.drop_index('idx_course_request_faculty')

    op.drop_table('course_requests')
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_index('idx_request_requester')
        batch_op.drop_index('idx_request_is_processed')
        batch_op.drop_index('idx_request_department')
        batch_op.drop_index('idx_request_activity_type')

    op.drop_table('requests')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_id'))
        batch_op.drop_index('idx_notification_user')
        batch_op.drop_index('idx_notification_read')
        batch_op.drop_index('idx_notification_importance')

    op.drop_table('notifications')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_id'))
        batch_op.drop_index('idx_comments_entity')
        batch_op.drop_index('idx_comments_author')

    op.drop_table('comments')
    op.drop_table('template_subservices')
    with op.batch_alter_table('professors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_professors_id'))
        batch_op.drop_index('idx_professor_department')

    op.drop_table('professors')
    with op.batch_alter_table('institutional_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_institutional_users_id'))
        batch_op.drop_index('idx_institutional_user_username')
        batch_op.drop_index('idx_institutional_user_is_active')
        batch_op.drop_index('idx_institutional_user_email')
        batch_op.drop_index('idx_institutional_user_department')

    op.drop_table('institutional_users')
    with op.batch_alter_table('careers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_careers_id'))
        batch_op.drop_index('idx_career_period')
        batch_op.drop_index('idx_career_department')
        batch_op.drop_index('idx_career_code')

    op.drop_table('careers')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index('idx_audit_log_user')
        batch_op.drop_index('idx_audit_log_timestamp')
        batch_op.drop_index('idx_audit_log_task_status')
        batch_op.drop_index('idx_audit_log_task_assignment')
        batch_op.drop_index('idx_audit_log_importance')
        batch_op.drop_index('idx_audit_log_entity')
        batch_op.drop_index('idx_audit_log_department')
        batch_op.drop_index('idx_audit_log_category')
        batch_op.drop_index('idx_audit_log_batch')
        batch_op.drop_index('idx_audit_log_action')

    op.drop_table('audit_logs')
    with op.batch_alter_table('work_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_items_id'))
        batch_op.drop_index('idx_work_item_status')
        batch_op.drop_index('idx_work_item_priority')
        batch_op.drop_index('idx_work_item_entity_type')

    op.drop_table('work_items')
    with op.batch_alter_table('user_two_factor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_two_factor_id'))
        batch_op.drop_index('idx_user_2fa_user')
        batch_op.drop_index('idx_user_2fa_method')
        batch_op.drop_index('idx_user_2fa_enabled')

    op.drop_table('user_two_factor')
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_index('idx_user_roles_user')
        batch_op.drop_index('idx_user_roles_role')
        batch_op.drop_index('idx_user_roles_area')

    op.drop_table('user_roles')
    op.drop_table('template_services')
    with op.batch_alter_table('tag_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_assignments_id'))
        batch_op.drop_index('idx_tag_assignment_tag')
        batch_op.drop_index('idx_tag_assignment_entity')

    op.drop_table('tag_assignments')
    with op.batch_alter_table('sub_services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sub_services_id'))

    op.drop_table('sub_services')
    with op.batch_alter_table('status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_status_history_id'))
        batch_op.drop_index('idx_status_history_user')
        batch_op.drop_index('idx_status_history_entity')
        batch_op.drop_index('idx_status_history_date')

    op.drop_table('status_history')
    with op.batch_alter_table('role_permissions', schema=None) as batch_op:
        batch_op.drop_index('idx_role_permissions_role')
        batch_op.drop_index('idx_role_permissions_permission')

    op.drop_table('role_permissions')
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_links_id'))
        batch_op.drop_index('idx_links_platform')
        batch_op.drop_index('idx_links_entity')

    op.drop_table('links')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_id'))

    op.drop_table('departments')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_id'))
        batch_op.drop_index('idx_attachments_uploader')
        batch_op.drop_index('idx_attachments_mime')
        batch_op.drop_index('idx_attachments_entity')

    op.drop_table('attachments')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index('idx_user_last_login')
        batch_op.drop_index('idx_user_join_date')
        batch_op.drop_index('idx_user_is_active')

    op.drop_table('users')
    with op.batch_alter_table('two_factor_methods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_two_factor_methods_id'))
        batch_op.drop_index('idx_2fa_method_code')
        batch_op.drop_index('idx_2fa_method_active')

    op.drop_table('two_factor_methods')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_id'))

    op.drop_table('tags')
    with op.batch_alter_table('statuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_statuses_id'))
        batch_op.drop_index('idx_status_level')
        batch_op.drop_index('idx_status_entity_type')

    op.drop_table('statuses')
    with op.batch_alter_table('smtp_configuration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_smtp_configuration_id'))

    op.drop_table('smtp_configuration')
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_id'))

    op.drop_table('services')
    with op.batch_alter_table('service_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_templates_id'))

    op.drop_table('service_templates')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_id'))

    op.drop_table('roles')
    with op.batch_alter_table('priorities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_priorities_id'))
        batch_op.drop_index('idx_priority_order')

    op.drop_table('priorities')
    with op.batch_alter_table('platforms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platforms_id'))

    op.drop_table('platforms')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permissions_id'))

    op.drop_table('permissions')
    with op.batch_alter_table('notification_triggers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_triggers_id'))

    op.drop_table('notification_triggers')
    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_templates_id'))

    op.drop_table('email_templates')
    with op.batch_alter_table('department_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_department_types_id'))

    op.drop_table('department_types')
    with op.batch_alter_table('areas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_areas_id'))

    op.drop_table('areas')
    with op.batch_alter_table('activity_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_types_id'))
        batch_op.drop_index('idx_activity_type_category')

    op.drop_table('activity_types')
    with op.batch_alter_table('academic_periods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_academic_periods_id'))
        batch_op.drop_index('idx_academic_period_code')
        batch_op.drop_index('idx_academic_period_active')

    op.drop_table('academic_periods')
    # ### end Alembic commands ###