"""add_service_templates

Revision ID: 8d8a8fa7f3a9
Revises: eec2e744e9ef
Create Date: 2025-05-06 22:04:14.222029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d8a8fa7f3a9'
down_revision = 'eec2e744e9ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_service_templates_id'), 'service_templates', ['id'], unique=False)
    op.create_table('template_services',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['service_templates.id'], ),
    sa.PrimaryKeyConstraint('template_id', 'service_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template_services')
    op.drop_index(op.f('ix_service_templates_id'), table_name='service_templates')
    op.drop_table('service_templates')
    # ### end Alembic commands ###