"""Refactor campos auditoria y notificaciones

Revision ID: a93a04f20bf2
Revises: 429801668f8f
Create Date: 2025-05-20 03:12:34.736726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a93a04f20bf2'
down_revision = '429801668f8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint('fk_projects_created_by_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_projects_updated_by_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_projects_deleted_by_id_users', type_='foreignkey')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('deleted_by_id')

    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_constraint('fk_requests_deleted_by_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_requests_updated_by_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_requests_created_by_id_users', type_='foreignkey')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('deleted_by_id')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_created_by_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_tasks_deleted_by_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_tasks_updated_by_id_users', type_='foreignkey')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('updated_by_id')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('deleted_by_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_by_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('deleted_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_by_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_tasks_updated_by_id_users', 'users', ['updated_by_id'], ['id'])
        batch_op.create_foreign_key('fk_tasks_deleted_by_id_users', 'users', ['deleted_by_id'], ['id'])
        batch_op.create_foreign_key('fk_tasks_created_by_id_users', 'users', ['created_by_id'], ['id'])

    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_by_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('deleted_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_by_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_requests_created_by_id_users', 'users', ['created_by_id'], ['id'])
        batch_op.create_foreign_key('fk_requests_updated_by_id_users', 'users', ['updated_by_id'], ['id'])
        batch_op.create_foreign_key('fk_requests_deleted_by_id_users', 'users', ['deleted_by_id'], ['id'])

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_by_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('deleted_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_by_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_projects_deleted_by_id_users', 'users', ['deleted_by_id'], ['id'])
        batch_op.create_foreign_key('fk_projects_updated_by_id_users', 'users', ['updated_by_id'], ['id'])
        batch_op.create_foreign_key('fk_projects_created_by_id_users', 'users', ['created_by_id'], ['id'])

    # ### end Alembic commands ###