"""Implement entity mixin and fix other relationships

Revision ID: b95f734f4816
Revises: 6433a101b3b5
Create Date: 2025-05-19 19:07:27.191294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b95f734f4816'
down_revision = '6433a101b3b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_entity_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('activity_entity_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_tasks_assignee_id_users'), 'users', ['assignee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tasks_assignee_id_users'), type_='foreignkey')
        batch_op.drop_column('activity_entity_id')
        batch_op.drop_column('activity_entity_type')

    # ### end Alembic commands ###