"""sincronizar_despues_de_eliminar_faculty

Revision ID: f76374452153
Revises: 43f0ce3aff2c
Create Date: 2025-05-19 23:46:18.977929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f76374452153'
down_revision = '43f0ce3aff2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professors', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_tasks_priority_id_priorities'), 'priorities', ['priority_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tasks_priority_id_priorities'), type_='foreignkey')
        batch_op.drop_column('priority_id')

    with op.batch_alter_table('professors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    # ### end Alembic commands ###